### ISSUE TITLE
About the R50-MS4 36epoch training result

### ISSUE THREAD

**Issue by cpsxhao** [IDEA-Research/DINO#104]
Hi, thank you for your great work! 

I was trying reproducing the results of 4-scale ResNet50 DINO model on COCO dataset. I trained in both FP16 and FP32, and the two experiments give the same result of 50.5 AP, which is a little bit lower than the reported 50.9 AP.

My initial LR is 1e-4 and LR drops at 30th epoch. The training log can be downloaded at 
https://drive.google.com/drive/folders/1yn7qOz0ViOSigyyj1JG3Pc2SISBk6bg7?usp=sharing

Could you help figure out the reason of the 0.4 AP gap? Looking forward to hearing from you!

**Comment by SuperHenry2333** [comment]
We picked a good epoch to drop lr. Our checkpoint is 48.9 before lr drop. We can try to drop from the epoch with the highest AP, which is 48.8 in your log.
