### ISSUE TITLE
About the design of the query in the model

### ISSUE THREAD

**Issue by davidyang180** [IDEA-Research/DINO#108]
Hi! I see that the design of the query in the code implementation only uses the learnable context embedding, and does not use the features output by the encoder for addition. Is there a difference in my understanding?
```
tgt_undetach = torch.gather(output_memory, 1, topk_proposals.unsqueeze(-1).repeat(1, 1, self.d_model))
            if self.embed_init_tgt:
                tgt_ = self.tgt_embed.weight[:, None, :].repeat(1, bs, 1).transpose(0, 1) # nq, bs, d_model
            else:
                tgt_ = tgt_undetach.detach()
```

**Comment by FengLi-ust** [comment]
Please refer to this [issue](https://github.com/IDEACVR/DINO/issues/4).
