### ISSUE TITLE
About two_stage_type  'enceachlayer', 'enclayer1'

### ISSUE THREAD

**Issue by sfwang20** [IDEA-Research/DINO#133]
Hi, thanks for your excellent work!
I saw you implement the two_stage_type  'enceachlayer' and  'enclayer1'.
I wonder the 'enceachlayer' and 'enclayer1' can help the model performance or not.
Besides, I also saw 'two_stage_pat_embed' and 'two_stage_add_query_num' which default values are both zero.
Does these help the model performance ?
Thank you very much.
Best regards.

**Comment by SuperHenry2333** [comment]
Hi, all these do not help performance. You can ignore them.
