### ISSUE TITLE
About 'backbone_freeze_keywords'

### ISSUE THREAD

**Issue by sfwang20** [IDEA-Research/DINO#135]
Hi! Thanks for your excellent work.
I wonder have you tried the args.backbone_freeze_keywords to freeze some layers in backbone?
Did it hurt the performance?
Thank you very much.

**Comment by SlongLiu** [comment]
Thanks for the question.
We provide the arg for more flexible modifications.

The performance depends on the backbone choice. 
For swinL, no freezed version worked best in our experiments.
