### ISSUE TITLE
What is the purpose of unsigmoid for output_proposals

### ISSUE THREAD

**Issue by weicheng113** [IDEA-Research/DINO#136]
Hi,

Thanks for sharing high performance model. I am going through the model source code and get a question about the use of unsigmoid in the following code.

https://github.com/IDEA-Research/DINO/blob/290cf6415166cc7cd0f68e5da973004e2f0e686b/models/dino/utils.py#L63

I tried the formula out and observed that sigmoid(unsigmoid(x)) = x. I wonder what the purpose of unsigmoid function here? I can see the value inside `output_proposals` are more spreaded out after unsigmoid(opposite sigmoid to squeeze the value into 0 and 1). Is 'more spreaded out values are easier to learn' the purpose of using unsigmoid here?

Thanks, 
Cheng

**Comment by SuperHenry2333** [comment]
@weicheng113 We need unsigmoid value because the layer-by-layer box refinement scheme requires adding two unsigmoid values and then using sigmoid to restrict the value to (0, 1).

**Comment by weicheng113** [comment]
@SuperHenry2333 Thanks for your time and reply. I will have a look.
