### ISSUE TITLE
Question about the extra norm layer 

### ISSUE THREAD

**Issue by ZRandomize** [IDEA-Research/DINO#147]
there is an extra norm layer [here](https://github.com/IDEA-Research/DINO/blob/66d7173cc4167934381a898b07c08507bdd96b63/models/dino/deformable_transformer.py#L755). Though there is already a layernorm after the FFN, this layer seems improved the final performance. How does it work? I can't find description in the paper.

**Comment by SlongLiu** [comment]
This implementation inherits from the conditional detr ([see here](https://github.com/Atten4Vis/ConditionalDETR/blob/main/models/transformer.py#L164)).  

We find it helps for the final performance. The extra layernorm can be viewed as an extra linear layer. I suspect the gains come from the extra parameters. 

Thanks for providing the interesting question. We will dive into it later.

**Comment by ZRandomize** [comment]
thx for your answer!

**Comment by sipie800** [comment]
> This implementation inherits from the conditional detr ([see here](https://github.com/Atten4Vis/ConditionalDETR/blob/main/models/transformer.py#L164)).
> 
> We find it helps for the final performance. The extra layernorm can be viewed as an extra linear layer. I suspect the gains come from the extra parameters.
> 
> Thanks for providing the interesting question. We will dive into it later.

Anyway, the weird thing is that the ref point is refined without an extra norm https://github.com/IDEA-Research/DINO/blob/d84a491d41898b3befd8294d1cf2614661fc0953/models/dino/deformable_transformer.py#L733. If use the same norm for the ref point, will it be even better?

**Comment by sipie800** [comment]
> > This implementation inherits from the conditional detr ([see here](https://github.com/Atten4Vis/ConditionalDETR/blob/main/models/transformer.py#L164)).
> > We find it helps for the final performance. The extra layernorm can be viewed as an extra linear layer. I suspect the gains come from the extra parameters.
> > Thanks for providing the interesting question. We will dive into it later.
> 
> Anyway, the weird thing is that the ref point is refined without an extra norm
> 
> [DINO/models/dino/deformable_transformer.py](https://github.com/IDEA-Research/DINO/blob/d84a491d41898b3befd8294d1cf2614661fc0953/models/dino/deformable_transformer.py#L733)
> 
> Line 733 in [d84a491](/IDEA-Research/DINO/commit/d84a491d41898b3befd8294d1cf2614661fc0953)
> 
>  delta_unsig = self.bbox_embed[layer_id](output) 
> . If use the same norm for the ref point, will it be even better?

I just do a real coco training, if add that extra norm to ref point updating as well. mAP has 0.5~1 gain. The extra norm significantly improves the coco medium and small objects.  I don't think original code is what it is supposed to be implemented, maybe just a forgotten detail.
