### ISSUE TITLE
Train Dino with focalNet backbone on custom datasets

### ISSUE THREAD

**Issue by 4BD0U** [IDEA-Research/DINO#156]
I am having difficulty training a Dino model with a FocalNet backbone on a custom dataset. Although I was able to successfully train the model using a SWIN-L backbone, after 10 epochs with FocalNet, all detection scores are still below 1%. I am unable to understand why this might be the case as the dataset used is identical and the pre-trained model provided in the GitHub repository was used as a starting point. Can you help me understand what might be causing this issue, please

**Comment by Hezey** [comment]
@4BD0U Hello, how to change backbone with others？Can you tell me ?please

**Comment by 4BD0U** [comment]
Thank you for your response. The problem was that the pre-trained model provided was meant for Dino 5scale with focalNet, while the configuration file was set up for Dino 4scale.

**Comment by 4BD0U** [comment]
> I simply used the implemented backbone and set up the configuration file.
