### ISSUE TITLE
About AP is all 0

### ISSUE THREAD

**Issue by chenxi-Guo** [IDEA-Research/DINO#167]
When I train a small target on my own dataset, I find that the AP value measured after running is all 0, what should I do？

**Comment by anantgupta129** [comment]
i have seen usually transformers take more data points, you can also make sure that you dataset is according to coco format

**Comment by HaoZhang534** [comment]
Can you provide more details like what is your dataset and the training log?

**Comment by chenxi-Guo** [comment]
Thanks for your reply.&nbsp;I have solved this problem, which was caused by improper data formatting.



---Original---
From: "Anant ***@***.***&gt;
Date: Tue, Mar 21, 2023 19:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IDEA-Research/DINO] About AP is all 0 (Issue #167)




 
i have seen usually transformers take more data points, you can also make sure that you dataset is according to coco format
