### ISSUE TITLE
Is there any way to get the coordinates(polygon shape returns)?

### ISSUE THREAD

**Issue by yellowjs0304** [IDEA-Research/DINO#171]
Hi, First of all Thank you for sharing nice work.
I'm beginner of DETR, and your model looks better than DETR.

I didn't check the detailed results yet, but i think this model also following DETR's output like bounding box (x, y, w, h).
Is there any way to get the polygon shaped bbox? (before : x, y, w, h -> after : x1, y1, x2, y2, x3, y3, x4, y4).

My dataset has not only rotated but also, distorted. 
I can also apply Segmentation task, but segmentation accuracy is really low in my data, so I can't get the contour of that segmentation mask.

If you have any ideas, please help me :)

**Comment by HaoZhang534** [comment]
Do you mean you want to predict distorted and rotated boxes? Our model does not support til now.

**Comment by yellowjs0304** [comment]
I got it. Thanks for reply.
