### ISSUE TITLE
The AP value is low

### ISSUE THREAD

**Issue by 1106X** [IDEA-Research/DINO#208]
Test:  [4990/5000]  eta: 0:00:01  class_error: 90.00  loss: 18.1650 (18.6082)  loss_bbox_dn: 0.0000 (0.0000)  loss_giou_dn: 0.0000 (0.0000)  loss_ce_dn: 0.0000 (0.0000)  loss_ce: 0.9389 (0.9540)  loss_bbox: 0.5480 (0.6824)  loss_gio
u: 0.9914 (1.0005)  loss_ce_0: 0.9541 (0.9501)  loss_bbox_0: 0.5749 (0.6957)  loss_giou_0: 1.0708 (1.0115)  loss_bbox_dn_0: 0.0000 (0.0000)  loss_giou_dn_0: 0.0000 (0.0000)  loss_ce_dn_0: 0.0000 (0.0000)  loss_ce_1: 0.9386 (0.9535) 
 loss_bbox_1: 0.5457 (0.6834)  loss_giou_1: 1.0185 (1.0027)  loss_bbox_dn_1: 0.0000 (0.0000)  loss_giou_dn_1: 0.0000 (0.0000)  loss_ce_dn_1: 0.0000 (0.0000)  loss_ce_2: 0.9471 (0.9546)  loss_bbox_2: 0.5535 (0.6815)  loss_giou_2: 1.0
117 (1.0001)  loss_bbox_dn_2: 0.0000 (0.0000)  loss_giou_dn_2: 0.0000 (0.0000)  loss_ce_dn_2: 0.0000 (0.0000)  loss_ce_3: 0.9385 (0.9502)  loss_bbox_3: 0.5266 (0.6842)  loss_giou_3: 0.9924 (0.9998)  loss_bbox_dn_3: 0.0000 (0.0000)  
loss_giou_dn_3: 0.0000 (0.0000)  loss_ce_dn_3: 0.0000 (0.0000)  loss_ce_4: 0.9348 (0.9552)  loss_bbox_4: 0.5235 (0.6833)  loss_giou_4: 0.9887 (1.0005)  loss_bbox_dn_4: 0.0000 (0.0000)  loss_giou_dn_4: 0.0000 (0.0000)  loss_ce_dn_4: 
0.0000 (0.0000)  loss_ce_interm: 0.9262 (0.9633)  loss_bbox_interm: 0.6536 (0.7635)  loss_giou_interm: 1.0469 (1.0381)  loss_bbox_dn_unscaled: 0.0000 (0.0000)  loss_giou_dn_unscaled: 0.0000 (0.0000)  loss_ce_dn_unscaled: 0.0000 (0.0
000)  loss_xy_dn_unscaled: 0.0000 (0.0000)  loss_hw_dn_unscaled: 0.0000 (0.0000)  cardinality_error_dn_unscaled: 0.0000 (0.0000)  loss_ce_unscaled: 0.9389 (0.9540)  class_error_unscaled: 90.0000 (74.5717)  loss_bbox_unscaled: 0.1096
 (0.1365)  loss_giou_unscaled: 0.4957 (0.5002)  loss_xy_unscaled: 0.0407 (0.0496)  loss_hw_unscaled: 0.0669 (0.0869)  cardinality_error_unscaled: 892.0000 (892.7283)  loss_ce_0_unscaled: 0.9541 (0.9501)  loss_bbox_0_unscaled: 0.1150
 (0.1391)  loss_giou_0_unscaled: 0.5354 (0.5058)  loss_xy_0_unscaled: 0.0390 (0.0503)  loss_hw_0_unscaled: 0.0789 (0.0889)  cardinality_error_0_unscaled: 892.0000 (892.7283)  loss_bbox_dn_0_unscaled: 0.0000 (0.0000)  loss_giou_dn_0_
unscaled: 0.0000 (0.0000)  loss_ce_dn_0_unscaled: 0.0000 (0.0000)  loss_xy_dn_0_unscaled: 0.0000 (0.0000)  loss_hw_dn_0_unscaled: 0.0000 (0.0000)  cardinality_error_dn_0_unscaled: 0.0000 (0.0000)  loss_ce_1_unscaled: 0.9386 (0.9535)
  loss_bbox_1_unscaled: 0.1091 (0.1367)  loss_giou_1_unscaled: 0.5092 (0.5014)  loss_xy_1_unscaled: 0.0399 (0.0495)  loss_hw_1_unscaled: 0.0691 (0.0872)  cardinality_error_1_unscaled: 892.0000 (892.7283)  loss_bbox_dn_1_unscaled: 0.
0000 (0.0000)  loss_giou_dn_1_unscaled: 0.0000 (0.0000)  loss_ce_dn_1_unscaled: 0.0000 (0.0000)  loss_xy_dn_1_unscaled: 0.0000 (0.0000)  loss_hw_dn_1_unscaled: 0.0000 (0.0000)  cardinality_error_dn_1_unscaled: 0.0000 (0.0000)  loss_
ce_2_unscaled: 0.9471 (0.9546)  loss_bbox_2_unscaled: 0.1107 (0.1363)  loss_giou_2_unscaled: 0.5059 (0.5000)  loss_xy_2_unscaled: 0.0422 (0.0493)  loss_hw_2_unscaled: 0.0728 (0.0870)  cardinality_error_2_unscaled: 892.0000 (892.7283
)  loss_bbox_dn_2_unscaled: 0.0000 (0.0000)  loss_giou_dn_2_unscaled: 0.0000 (0.0000)  loss_ce_dn_2_unscaled: 0.0000 (0.0000)  loss_xy_dn_2_unscaled: 0.0000 (0.0000)  loss_hw_dn_2_unscaled: 0.0000 (0.0000)  cardinality_error_dn_2_un
scaled: 0.0000 (0.0000)  loss_ce_3_unscaled: 0.9385 (0.9502)  loss_bbox_3_unscaled: 0.1053 (0.1368)  loss_giou_3_unscaled: 0.4962 (0.4999)  loss_xy_3_unscaled: 0.0407 (0.0496)  loss_hw_3_unscaled: 0.0641 (0.0872)  cardinality_error_
3_unscaled: 892.0000 (892.7283)  loss_bbox_dn_3_unscaled: 0.0000 (0.0000)  loss_giou_dn_3_unscaled: 0.0000 (0.0000)  loss_ce_dn_3_unscaled: 0.0000 (0.0000)  loss_xy_dn_3_unscaled: 0.0000 (0.0000)  loss_hw_dn_3_unscaled: 0.0000 (0.00
00)  cardinality_error_dn_3_unscaled: 0.0000 (0.0000)  loss_ce_4_unscaled: 0.9348 (0.9552)  loss_bbox_4_unscaled: 0.1047 (0.1367)  loss_giou_4_unscaled: 0.4943 (0.5002)  loss_xy_4_unscaled: 0.0407 (0.0496)  loss_hw_4_unscaled: 0.064
8 (0.0870)  cardinality_error_4_unscaled: 892.0000 (892.7283)  loss_bbox_dn_4_unscaled: 0.0000 (0.0000)  loss_giou_dn_4_unscaled: 0.0000 (0.0000)  loss_ce_dn_4_unscaled: 0.0000 (0.0000)  loss_xy_dn_4_unscaled: 0.0000 (0.0000)  loss_
hw_dn_4_unscaled: 0.0000 (0.0000)  cardinality_error_dn_4_unscaled: 0.0000 (0.0000)  loss_ce_interm_unscaled: 0.9262 (0.9633)  loss_bbox_interm_unscaled: 0.1307 (0.1527)  loss_giou_interm_unscaled: 0.5235 (0.5191)  loss_xy_interm_unscaled: 0.0430 (0.0531)  loss_hw_interm_unscaled: 0.0882 (0.0996)  cardinality_error_interm_unscaled: 892.0000 (892.7283)  time: 0.1191  data: 0.0018  max mem: 11092
Test:  [4999/5000]  eta: 0:00:00  class_error: 100.00  loss: 18.4705 (18.6084)  loss_bbox_dn: 0.0000 (0.0000)  loss_giou_dn: 0.0000 (0.0000)  loss_ce_dn: 0.0000 (0.0000)  loss_ce: 0.9389 (0.9542)  loss_bbox: 0.5905 (0.6824)  loss_gi
ou: 1.0163 (1.0004)  loss_ce_0: 0.9541 (0.9502)  loss_bbox_0: 0.6714 (0.6957)  loss_giou_0: 1.1055 (1.0114)  loss_bbox_dn_0: 0.0000 (0.0000)  loss_giou_dn_0: 0.0000 (0.0000)  loss_ce_dn_0: 0.0000 (0.0000)  loss_ce_1: 0.9422 (0.9536)
  loss_bbox_1: 0.6317 (0.6834)  loss_giou_1: 1.0207 (1.0026)  loss_bbox_dn_1: 0.0000 (0.0000)  loss_giou_dn_1: 0.0000 (0.0000)  loss_ce_dn_1: 0.0000 (0.0000)  loss_ce_2: 0.9515 (0.9547)  loss_bbox_2: 0.6606 (0.6816)  loss_giou_2: 1.
0299 (1.0000)  loss_bbox_dn_2: 0.0000 (0.0000)  loss_giou_dn_2: 0.0000 (0.0000)  loss_ce_dn_2: 0.0000 (0.0000)  loss_ce_3: 0.9479 (0.9503)  loss_bbox_3: 0.5948 (0.6842)  loss_giou_3: 1.0124 (0.9998)  loss_bbox_dn_3: 0.0000 (0.0000) 
 loss_giou_dn_3: 0.0000 (0.0000)  loss_ce_dn_3: 0.0000 (0.0000)  loss_ce_4: 0.9387 (0.9553)  loss_bbox_4: 0.5942 (0.6832)  loss_giou_4: 1.0102 (1.0004)  loss_bbox_dn_4: 0.0000 (0.0000)  loss_giou_dn_4: 0.0000 (0.0000)  loss_ce_dn_4:
 0.0000 (0.0000)  loss_ce_interm: 0.9747 (0.9634)  loss_bbox_interm: 0.6450 (0.7636)  loss_giou_interm: 1.0772 (1.0381)  loss_bbox_dn_unscaled: 0.0000 (0.0000)  loss_giou_dn_unscaled: 0.0000 (0.0000)  loss_ce_dn_unscaled: 0.0000 (0.
0000)  loss_xy_dn_unscaled: 0.0000 (0.0000)  loss_hw_dn_unscaled: 0.0000 (0.0000)  cardinality_error_dn_unscaled: 0.0000 (0.0000)  loss_ce_unscaled: 0.9389 (0.9542)  class_error_unscaled: 88.8889 (74.5565)  loss_bbox_unscaled: 0.118
1 (0.1365)  loss_giou_unscaled: 0.5082 (0.5002)  loss_xy_unscaled: 0.0407 (0.0496)  loss_hw_unscaled: 0.0730 (0.0869)  cardinality_error_unscaled: 895.0000 (892.7330)  loss_ce_0_unscaled: 0.9541 (0.9502)  loss_bbox_0_unscaled: 0.134
3 (0.1391)  loss_giou_0_unscaled: 0.5528 (0.5057)  loss_xy_0_unscaled: 0.0390 (0.0503)  loss_hw_0_unscaled: 0.0875 (0.0889)  cardinality_error_0_unscaled: 895.0000 (892.7330)  loss_bbox_dn_0_unscaled: 0.0000 (0.0000)  loss_giou_dn_0
_unscaled: 0.0000 (0.0000)  loss_ce_dn_0_unscaled: 0.0000 (0.0000)  loss_xy_dn_0_unscaled: 0.0000 (0.0000)  loss_hw_dn_0_unscaled: 0.0000 (0.0000)  cardinality_error_dn_0_unscaled: 0.0000 (0.0000)  loss_ce_1_unscaled: 0.9422 (0.9536
)  loss_bbox_1_unscaled: 0.1263 (0.1367)  loss_giou_1_unscaled: 0.5104 (0.5013)  loss_xy_1_unscaled: 0.0384 (0.0495)  loss_hw_1_unscaled: 0.0789 (0.0872)  cardinality_error_1_unscaled: 895.0000 (892.7330)  loss_bbox_dn_1_unscaled: 0
.0000 (0.0000)  loss_giou_dn_1_unscaled: 0.0000 (0.0000)  loss_ce_dn_1_unscaled: 0.0000 (0.0000)  loss_xy_dn_1_unscaled: 0.0000 (0.0000)  loss_hw_dn_1_unscaled: 0.0000 (0.0000)  cardinality_error_dn_1_unscaled: 0.0000 (0.0000)  loss
_ce_2_unscaled: 0.9515 (0.9547)  loss_bbox_2_unscaled: 0.1321 (0.1363)  loss_giou_2_unscaled: 0.5149 (0.5000)  loss_xy_2_unscaled: 0.0406 (0.0493)  loss_hw_2_unscaled: 0.0783 (0.0870)  cardinality_error_2_unscaled: 895.0000 (892.733
0)  loss_bbox_dn_2_unscaled: 0.0000 (0.0000)  loss_giou_dn_2_unscaled: 0.0000 (0.0000)  loss_ce_dn_2_unscaled: 0.0000 (0.0000)  loss_xy_dn_2_unscaled: 0.0000 (0.0000)  loss_hw_dn_2_unscaled: 0.0000 (0.0000)  cardinality_error_dn_2_u
nscaled: 0.0000 (0.0000)  loss_ce_3_unscaled: 0.9479 (0.9503)  loss_bbox_3_unscaled: 0.1190 (0.1368)  loss_giou_3_unscaled: 0.5062 (0.4999)  loss_xy_3_unscaled: 0.0402 (0.0496)  loss_hw_3_unscaled: 0.0766 (0.0873)  cardinality_error
_3_unscaled: 895.0000 (892.7330)  loss_bbox_dn_3_unscaled: 0.0000 (0.0000)  loss_giou_dn_3_unscaled: 0.0000 (0.0000)  loss_ce_dn_3_unscaled: 0.0000 (0.0000)  loss_xy_dn_3_unscaled: 0.0000 (0.0000)  loss_hw_dn_3_unscaled: 0.0000 (0.0
000)  cardinality_error_dn_3_unscaled: 0.0000 (0.0000)  loss_ce_4_unscaled: 0.9387 (0.9553)  loss_bbox_4_unscaled: 0.1188 (0.1366)  loss_giou_4_unscaled: 0.5051 (0.5002)  loss_xy_4_unscaled: 0.0407 (0.0496)  loss_hw_4_unscaled: 0.07
37 (0.0870)  cardinality_error_4_unscaled: 895.0000 (892.7330)  loss_bbox_dn_4_unscaled: 0.0000 (0.0000)  loss_giou_dn_4_unscaled: 0.0000 (0.0000)  loss_ce_dn_4_unscaled: 0.0000 (0.0000)  loss_xy_dn_4_unscaled: 0.0000 (0.0000)  loss
_hw_dn_4_unscaled: 0.0000 (0.0000)  cardinality_error_dn_4_unscaled: 0.0000 (0.0000)  loss_ce_interm_unscaled: 0.9747 (0.9634)  loss_bbox_interm_unscaled: 0.1290 (0.1527)  loss_giou_interm_unscaled: 0.5386 (0.5190)  loss_xy_interm_unscaled: 0.0398 (0.0531)  loss_hw_interm_unscaled: 0.0934 (0.0996)  cardinality_error_interm_unscaled: 895.0000 (892.7330)  time: 0.1168  data: 0.0018  max mem: 11092
Test: Total time: 0:12:17 (0.1476 s / it)
Averaged stats: class_error: 100.00  loss: 18.4705 (18.6084)  loss_bbox_dn: 0.0000 (0.0000)  loss_giou_dn: 0.0000 (0.0000)  loss_ce_dn: 0.0000 (0.0000)  loss_ce: 0.9389 (0.9542)  loss_bbox: 0.5905 (0.6824)  loss_giou: 1.0163 (1.0004
)  loss_ce_0: 0.9541 (0.9502)  loss_bbox_0: 0.6714 (0.6957)  loss_giou_0: 1.1055 (1.0114)  loss_bbox_dn_0: 0.0000 (0.0000)  loss_giou_dn_0: 0.0000 (0.0000)  loss_ce_dn_0: 0.0000 (0.0000)  loss_ce_1: 0.9422 (0.9536)  loss_bbox_1: 0.6
317 (0.6834)  loss_giou_1: 1.0207 (1.0026)  loss_bbox_dn_1: 0.0000 (0.0000)  loss_giou_dn_1: 0.0000 (0.0000)  loss_ce_dn_1: 0.0000 (0.0000)  loss_ce_2: 0.9515 (0.9547)  loss_bbox_2: 0.6606 (0.6816)  loss_giou_2: 1.0299 (1.0000)  los
s_bbox_dn_2: 0.0000 (0.0000)  loss_giou_dn_2: 0.0000 (0.0000)  loss_ce_dn_2: 0.0000 (0.0000)  loss_ce_3: 0.9479 (0.9503)  loss_bbox_3: 0.5948 (0.6842)  loss_giou_3: 1.0124 (0.9998)  loss_bbox_dn_3: 0.0000 (0.0000)  loss_giou_dn_3: 0
.0000 (0.0000)  loss_ce_dn_3: 0.0000 (0.0000)  loss_ce_4: 0.9387 (0.9553)  loss_bbox_4: 0.5942 (0.6832)  loss_giou_4: 1.0102 (1.0004)  loss_bbox_dn_4: 0.0000 (0.0000)  loss_giou_dn_4: 0.0000 (0.0000)  loss_ce_dn_4: 0.0000 (0.0000)  
loss_ce_interm: 0.9747 (0.9634)  loss_bbox_interm: 0.6450 (0.7636)  loss_giou_interm: 1.0772 (1.0381)  loss_bbox_dn_unscaled: 0.0000 (0.0000)  loss_giou_dn_unscaled: 0.0000 (0.0000)  loss_ce_dn_unscaled: 0.0000 (0.0000)  loss_xy_dn_
unscaled: 0.0000 (0.0000)  loss_hw_dn_unscaled: 0.0000 (0.0000)  cardinality_error_dn_unscaled: 0.0000 (0.0000)  loss_ce_unscaled: 0.9389 (0.9542)  class_error_unscaled: 88.8889 (74.5565)  loss_bbox_unscaled: 0.1181 (0.1365)  loss_g
iou_unscaled: 0.5082 (0.5002)  loss_xy_unscaled: 0.0407 (0.0496)  loss_hw_unscaled: 0.0730 (0.0869)  cardinality_error_unscaled: 895.0000 (892.7330)  loss_ce_0_unscaled: 0.9541 (0.9502)  loss_bbox_0_unscaled: 0.1343 (0.1391)  loss_g
iou_0_unscaled: 0.5528 (0.5057)  loss_xy_0_unscaled: 0.0390 (0.0503)  loss_hw_0_unscaled: 0.0875 (0.0889)  cardinality_error_0_unscaled: 895.0000 (892.7330)  loss_bbox_dn_0_unscaled: 0.0000 (0.0000)  loss_giou_dn_0_unscaled: 0.0000 
(0.0000)  loss_ce_dn_0_unscaled: 0.0000 (0.0000)  loss_xy_dn_0_unscaled: 0.0000 (0.0000)  loss_hw_dn_0_unscaled: 0.0000 (0.0000)  cardinality_error_dn_0_unscaled: 0.0000 (0.0000)  loss_ce_1_unscaled: 0.9422 (0.9536)  loss_bbox_1_uns
caled: 0.1263 (0.1367)  loss_giou_1_unscaled: 0.5104 (0.5013)  loss_xy_1_unscaled: 0.0384 (0.0495)  loss_hw_1_unscaled: 0.0789 (0.0872)  cardinality_error_1_unscaled: 895.0000 (892.7330)  loss_bbox_dn_1_unscaled: 0.0000 (0.0000)  lo
ss_giou_dn_1_unscaled: 0.0000 (0.0000)  loss_ce_dn_1_unscaled: 0.0000 (0.0000)  loss_xy_dn_1_unscaled: 0.0000 (0.0000)  loss_hw_dn_1_unscaled: 0.0000 (0.0000)  cardinality_error_dn_1_unscaled: 0.0000 (0.0000)  loss_ce_2_unscaled: 0.
9515 (0.9547)  loss_bbox_2_unscaled: 0.1321 (0.1363)  loss_giou_2_unscaled: 0.5149 (0.5000)  loss_xy_2_unscaled: 0.0406 (0.0493)  loss_hw_2_unscaled: 0.0783 (0.0870)  cardinality_error_2_unscaled: 895.0000 (892.7330)  loss_bbox_dn_2
_unscaled: 0.0000 (0.0000)  loss_giou_dn_2_unscaled: 0.0000 (0.0000)  loss_ce_dn_2_unscaled: 0.0000 (0.0000)  loss_xy_dn_2_unscaled: 0.0000 (0.0000)  loss_hw_dn_2_unscaled: 0.0000 (0.0000)  cardinality_error_dn_2_unscaled: 0.0000 (0
.0000)  loss_ce_3_unscaled: 0.9479 (0.9503)  loss_bbox_3_unscaled: 0.1190 (0.1368)  loss_giou_3_unscaled: 0.5062 (0.4999)  loss_xy_3_unscaled: 0.0402 (0.0496)  loss_hw_3_unscaled: 0.0766 (0.0873)  cardinality_error_3_unscaled: 895.0
000 (892.7330)  loss_bbox_dn_3_unscaled: 0.0000 (0.0000)  loss_giou_dn_3_unscaled: 0.0000 (0.0000)  loss_ce_dn_3_unscaled: 0.0000 (0.0000)  loss_xy_dn_3_unscaled: 0.0000 (0.0000)  loss_hw_dn_3_unscaled: 0.0000 (0.0000)  cardinality_
error_dn_3_unscaled: 0.0000 (0.0000)  loss_ce_4_unscaled: 0.9387 (0.9553)  loss_bbox_4_unscaled: 0.1188 (0.1366)  loss_giou_4_unscaled: 0.5051 (0.5002)  loss_xy_4_unscaled: 0.0407 (0.0496)  loss_hw_4_unscaled: 0.0737 (0.0870)  cardi
nality_error_4_unscaled: 895.0000 (892.7330)  loss_bbox_dn_4_unscaled: 0.0000 (0.0000)  loss_giou_dn_4_unscaled: 0.0000 (0.0000)  loss_ce_dn_4_unscaled: 0.0000 (0.0000)  loss_xy_dn_4_unscaled: 0.0000 (0.0000)  loss_hw_dn_4_unscaled:
 0.0000 (0.0000)  cardinality_error_dn_4_unscaled: 0.0000 (0.0000)  loss_ce_interm_unscaled: 0.9747 (0.9634)  loss_bbox_interm_unscaled: 0.1290 (0.1527)  loss_giou_interm_unscaled: 0.5386 (0.5190)  loss_xy_interm_unscaled: 0.0398 (0.0531)  loss_hw_interm_unscaled: 0.0934 (0.0996)  cardinality_error_interm_unscaled: 895.0000 (892.7330)
Accumulating evaluation results...
DONE (t=25.48s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.010
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.015
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.016
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.027

**Comment by inSight-mk1** [comment]
看你项目是中文，就直接用中文说了。
和你一样的，我是自定义数据集，按coco格式转的，train时val结果是正常的，test就全零了，不知道哪里错了

**Comment by 1106X** [comment]
> 看你项目是中文，就直接用中文说了。 和你一样的，我是自定义数据集，按coco格式转的，train时val结果是正常的，test就全零了，不知道哪里错了

我使用的是coco2017数据集  并且使用这个数据集在作者实验室前期工作DAB-DETR的时候一切正常   在这个工作中才出现了问题 并且我没更改任何设置 只对数据集路径、bs和numwork做了改变  我在train时val的结果也是这样 莫名其妙的错误

**Comment by Ferry7z** [comment]
请问解决了吗，我也遇到了同样的问题

**Comment by maichm** [comment]
训练自定义数据时，用resnet backbone似乎是正常的。同样的数据换swim backbone也出现了这个情况

**Comment by letmejoin** [comment]
遇到了同样的问题，训练自己数据，用cascade-rcnn-x101 AP50可以到80多，但是DINO相同的backbone，AP50只有40多，一直找不到啥原因

**Comment by maichm** [comment]
> 训练自定义数据时，用resnet backbone似乎是正常的。同样的数据换swim backbone也出现了这个情况


用了pretrain模型之后效果就提升了很多

**Comment by EddieEduardo** [comment]
请问这个转换的json文件是xyxy格式还是xywh格式呢？

**Comment by FengLi-ust** [comment]
train的时候发现val数据集上结果很差吗？在coco上能否复现我们的结果呢？

**Comment by lastwhisper-ghy** [comment]
> 请问解决了吗，我也遇到了同样的问题

你好，解决了吗，我也是这样，我在用focalnet-dino微调时出现ap很低的情况
