### ISSUE TITLE
大佬，您好！  性能最优

### ISSUE THREAD

**Issue by sdreamforchen** [IDEA-Research/DINO#209]
大佬，您好，如果追求性能最优，如何配置超参合适呢？ 目前训练几个epoch就达到很好的精度，如果想更好呢

**Comment by xx025** [comment]
可以试试24个epoch , 论文中的对比实验就是使用24个epoch
![image](https://github.com/IDEA-Research/DINO/assets/71559822/b42c641d-b6c3-48da-8935-d94a38f0a073)

下面是我在自己的数据集上测试的
![image](https://github.com/IDEA-Research/DINO/assets/71559822/92ae46c7-69e0-4fd3-b8b0-1b23ba46b00e)

**Comment by FengLi-ust** [comment]
现在的超参数就可以了。
