### ISSUE TITLE
take the wrong path towards the checkpoint, when resuming the model

### ISSUE THREAD

**Issue by eatmore18** [IDEA-Research/DINO#214]

**Comment by eatmore18** [comment]
When I resume the model by providing the checkpoint path as an argument, I consistently obtain identical validation results for different checkpoints. After realizing the issue, I found that these two lines of code are the cause of the problem. What is the purpose or functionality of these two lines of code?
https://github.com/IDEA-Research/DINO/blob/69f0d5e3c8d8cbb6c0f4ed7bc1f518a8bfb8f8b2/main.py#L205-L206

**Comment by FengLi-ust** [comment]
Hi, this is just to load the latest checkpoint in one directory. If you rerun the model, please select another directory.
