### ISSUE TITLE
RuntimeError: No shared folder available

### ISSUE THREAD

**Issue by rocketsfallonrocketfalls** [IDEA-Research/DINO#80]
Hey, 

I am glad the code is finally available and I am more than excited to play with the repo. I can work with the smallest model and it runs well.

But when I attempt to train a model with "swin_large_patch4_window12_384_22k.pth" backbone using "scripts/DINO_train_submitit_swin.sh" I am getting the error in the title and I have no idea what should that mean. 

I am running everything in a docker container if that is relevant. 

Thanks a lot!

**Comment by SlongLiu** [comment]
#66 might be helpful to the problem.
