### ISSUE TITLE
Traning and Testing with own data set and visualize them

### ISSUE THREAD

**Issue by CATAKIDOKI** [IDEA-Research/DINO#89]
Hello, First of all, congratulations on your work and thanks a lot. I am pretty new to object detection and so, some terms seem pretty foreign to me.  I am using your DINO model for my project assignment but I couldn't figure out how to train with our own dataset, even though I read previous issues. I didn't fully understand the steps, it was a bit complicated for me. Could you please explain detailed or share an article or video in which you explain  how we manipulate our own data for traning and testing, what stages we go through afterwards, and how we can visualize it as a result, in detail and step by step. It will be good for those who want to progress on this subject like me but do not have much knowledge.

**Comment by SlongLiu** [comment]
Thanks for your suggestions.

For testing and visualization, you can refer to this notebook: https://github.com/IDEACVR/DINO/blob/main/inference_and_visualization.ipynb.


We update the run section, https://github.com/IDEACVR/DINO#run, with a new section for custom dataset training.


Hope the notes are helpful.
